import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Background from "@/components/Background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "4ONE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* PAGE WRAPPER */}
        <div className="relative min-h-screen flex flex-col">

          {/* BACKGROUND */}
          <div className="fixed inset-0 -z-10 pointer-events-none">
            <Background />
          </div>

          <Header />

          <main className="flex-1 relative z-10">
            {children}
          </main>

          <Footer />

        </div>
      </body>
    </html>
  );
}
