import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "4ONE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}>

{/* Background */}
<div className="fixed inset-0 -z-10 bg-gradient-to-br from-zinc-950 via-indigo-950 to-zinc-950" />


          <Header />

          <main className="flex-grow">
            {children}
          </main>

          <Footer />
      </body>
    </html>
  );
}

